version: '2.3'

services:
  postgres:
    image: postgres:13
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: teodorriyce/kittygram_backend:latest
    environment:
      - POSTGRES_DBNAME=microsoft_ads
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy