name: Kittigram workflows

defaults:
  run:
    shell: bash

on:
  push:
    branches:
    - main

env:
  DOCKER_BUILDKIT: 1

jobs:
  lint_and_test_backend_service:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: make deps-dev

      - name: Run lint
        run: make lint

#      - name: Run tests
#        run: make test



