name: Kittigram workflows

defaults:
  run:
    shell: bash

on:
  push:
    branches:
    - main

env:
  POSTGRES_USER: postgres_user
  POSTGRES_DB: kittygram
  POSTGRES_PASSWORD: postgres_password
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432
  POSTGRES_HOST_AUTH_METHOD: trust

jobs:
  lint_and_test_backend_service:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_HOST }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: make deps-dev

      - name: Run lint
        run: make backend-lint

      - name: Run tests
        run: make backend-test
