name: Kittigram workflows

defaults:
  run:
    shell: bash

on:
  push:
    branches:
    - main

env:
  SERVICE: kittygram_backend
  POSTGRES_USER: postgres_user
  POSTGRES_DB: kittygram
  POSTGRES_PASSWORD: postgres_password
  POSTGRES_HOST: 127.0.0.1
  POSTGRES_PORT: 5432
  POSTGRES_HOST_AUTH_METHOD: trust

jobs:
  lint_and_test_backend_service:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: make deps-dev

      - name: Run lint
        run: make backend-lint

  build_and_push_to_docker_hub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    needs: lint_and_test_backend_service
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ env.SERVICE }}:latest
